#!/bin/sh

shortseason=2014
shortyear=$((shortseason+1))
season="${shortseason}-${shortyear:2:2}"

curl --create-dirs -# -o data/stats/$season/speed.json       -# "http://stats.nba.com/js/data/sportvu/$shortseason/speedData.json"
curl --create-dirs -# -o data/stats/$season/touches.json     -# "http://stats.nba.com/js/data/sportvu/$shortseason/touchesData.json"
curl --create-dirs -# -o data/stats/$season/passing.json     -# "http://stats.nba.com/js/data/sportvu/$shortseason/passingData.json"
curl --create-dirs -# -o data/stats/$season/defense.json     -# "http://stats.nba.com/js/data/sportvu/$shortseason/defenseData.json"
curl --create-dirs -# -o data/stats/$season/rebounding.json  -# "http://stats.nba.com/js/data/sportvu/$shortseason/reboundingData.json"
curl --create-dirs -# -o data/stats/$season/drives.json      -# "http://stats.nba.com/js/data/sportvu/$shortseason/drivesData.json"
curl --create-dirs -# -o data/stats/$season/catch-shoot.json -# "http://stats.nba.com/js/data/sportvu/$shortseason/catchShootData.json"
curl --create-dirs -# -o data/stats/$season/pull-ups.json    -# "http://stats.nba.com/js/data/sportvu/$shortseason/pullUpShootData.json"
curl --create-dirs -# -o data/stats/$season/shooting.json    -# "http://stats.nba.com/js/data/sportvu/$shortseason/shootingData.json"
