#!/bin/sh

curl -o data/stats/speed.js       -# 'http://stats.nba.com/js/data/sportvu/speedData.js'
curl -o data/stats/touches.js     -# 'http://stats.nba.com/js/data/sportvu/touchesData.js'
curl -o data/stats/passing.js     -# 'http://stats.nba.com/js/data/sportvu/passingData.js'
curl -o data/stats/defense.js     -# 'http://stats.nba.com/js/data/sportvu/defenseData.js'
curl -o data/stats/rebounding.js  -# 'http://stats.nba.com/js/data/sportvu/reboundingData.js'
curl -o data/stats/drives.js      -# 'http://stats.nba.com/js/data/sportvu/drivesData.js'
curl -o data/stats/catch-shoot.js -# 'http://stats.nba.com/js/data/sportvu/catchShootData.js'
curl -o data/stats/pull-ups.js    -# 'http://stats.nba.com/js/data/sportvu/pullUpShootData.js'
curl -o data/stats/shooting.js    -# 'http://stats.nba.com/js/data/sportvu/shootingData.js'

